import {
  Home,
  Laugh,
  Type,
  LoaderCircle,
  ToggleLeft,
  Workflow,
  RotateCcwSquare,
  Rows3,
  Sparkles,
  KeyRound,
  Wallet,
  ScanSearch,
  Cat,
  ArrowUpDown,
  Filter,
  CalendarDays,
  List,
  Trophy,
  Hand,
  PencilRuler,
  LayoutGrid,
  Link2,
} from 'lucide-react';

// Central route metadata keeps the sidebar and route shell in sync.
export const buildRegistry = [
  {
    name: 'Home',
    link: '',
    path: '/',
    active: true,
    icon: Home,
    accent: 'var(--accent-primary)',
    description: 'Landing page for the mini-build library.',
  },
  {
    name: 'Chuck Norris Jokes',
    link: 'chuckNorris',
    path: '/chuckNorris',
    icon: Laugh,
    accent: 'var(--accent-secondary)',
    description: 'Browse Chuck Norris jokes, switch categories, and refresh punchlines quickly.',
  },
  {
    name: 'Animated Text',
    link: 'animatedText',
    path: '/animatedText',
    icon: Type,
    accent: 'var(--accent-primary)',
    description: 'Preview animated text styles, tune sizing, and test motion treatments on custom copy.',
  },
  {
    name: 'Loaders',
    link: 'loaders',
    path: '/loaders',
    icon: LoaderCircle,
    accent: 'var(--accent-secondary)',
    description: 'Compare loading patterns, progress states, and delayed data-fetch feedback in one place.',
  },
  {
    name: 'Truthy',
    link: 'truthy',
    path: '/truthy',
    icon: ToggleLeft,
    accent: 'var(--accent-primary)',
    description: 'Explore truthy state handling, toggle feedback, and conditional UI reactions.',
  },
  {
    name: 'Flow Diagrams',
    link: 'reactflow',
    path: '/reactflow',
    icon: Workflow,
    accent: 'var(--accent-secondary)',
    description: 'Build and inspect interactive node diagrams with editable React Flow connections.',
  },
  {
    name: 'Flip This',
    link: 'flip',
    path: '/flip',
    icon: RotateCcwSquare,
    accent: 'var(--accent-primary)',
    description: 'Test a lightweight card-flip game flow with reveal, reset, and interaction feedback.',
  },
  {
    name: 'Expanded',
    link: 'expand',
    path: '/expand',
    icon: Rows3,
    accent: 'var(--accent-secondary)',
    description: 'Open and collapse layered content panels to test expandable section behaviour.',
  },
  {
    name: 'Pokemon API',
    link: 'pokemon',
    path: '/pokemon',
    icon: Sparkles,
    accent: 'var(--accent-primary)',
    description: 'Search Pokémon, preview card details, and open a richer modal for stats, cries, and media.',
  },
  {
    name: 'Password Gen',
    link: 'passGen',
    path: '/passGen',
    icon: KeyRound,
    accent: 'var(--accent-secondary)',
    description: 'Generate passwords with adjustable character rules and quick copy actions.',
  },
  {
    name: 'I & E',
    link: 'IandE',
    path: '/IandE',
    icon: Wallet,
    accent: 'var(--accent-primary)',
    description: 'Track income, expenses, savings, and monthly cash flow with local-storage persistence.',
  },
  {
    name: 'RIO API',
    link: 'IOP',
    path: '/IOP',
    icon: ScanSearch,
    accent: 'var(--accent-secondary)',
    description: 'See how intersection observer triggers content changes as sections enter the viewport.',
  },
  {
    name: 'Kitty API',
    link: 'cat',
    path: '/cat',
    icon: Cat,
    accent: 'var(--accent-primary)',
    description: 'Load random cat media, preview fetched results, and test lightweight API gallery behaviour.',
  },
  {
    name: 'Sortables',
    link: 'sort',
    path: '/sort',
    icon: ArrowUpDown,
    accent: 'var(--accent-secondary)',
    description: 'Move people between queues and test sortable list behaviour with live ordering updates.',
  },
  {
    name: 'Filters',
    link: 'filters',
    path: '/filters',
    icon: Filter,
    accent: 'var(--accent-primary)',
    description: 'Filter a larger table dataset, narrow the results, and export selected rows.',
  },
  {
    name: 'Date Pickers',
    link: 'datepickers',
    path: '/datepickers',
    icon: CalendarDays,
    accent: 'var(--accent-secondary)',
    description: 'Compare date input components, range selection, and shortcut-driven picker flows.',
  },
  {
    name: 'Virtualized List',
    link: 'virtualized',
    path: '/virtualized',
    icon: List,
    accent: 'var(--accent-primary)',
    description: 'Render long datasets efficiently with virtualization and worker-assisted data generation.',
  },
  {
    name: 'Leaderboard',
    link: 'leaderboard',
    path: '/leaderboard',
    icon: Trophy,
    accent: 'var(--accent-secondary)',
    description: 'View a reshuffling leaderboard with ranked performance metrics and table-style comparison.',
  },
  {
    name: 'CardSwap',
    link: 'cardswap',
    path: '/cardswap',
    icon: Hand,
    accent: 'var(--accent-primary)',
    description: 'Reorder image cards in a freeform drag layout and persist the arrangement locally.',
  },
  {
    name: 'Edit Section',
    link: 'editsection',
    path: '/editsection',
    icon: PencilRuler,
    accent: 'var(--accent-secondary)',
    description: 'Reorder editable content blocks and experiment with a simple visual section editor.',
  },

  {
    name: 'Drive Links',
    link: 'drivelinks',
    path: '/drivelinks',
    icon: Link2,
    accent: 'var(--accent-secondary)',
    description: 'Convert Drive share links, preview supported media, and batch-copy grouped output URLs.',
  },
  {
    name: 'DND Grid',
    link: 'dndgrid',
    path: '/dndgrid',
    icon: LayoutGrid,
    accent: 'var(--accent-primary)',
    description: 'Drag profile cards around a masonry-style grid and keep the saved order locally.',
  },
];
