import {
  Home,
  Laugh,
  Type,
  LoaderCircle,
  ToggleLeft,
  Workflow,
  RotateCcwSquare,
  Rows3,
  Sparkles,
  KeyRound,
  Wallet,
  ScanSearch,
  Cat,
  ArrowUpDown,
  Filter,
  CalendarDays,
  List,
  Trophy,
  Hand,
  PencilRuler,
  LayoutGrid,
} from 'lucide-react';

// Central route metadata keeps the sidebar and route shell in sync.
export const buildRegistry = [
  {
    name: 'Home',
    link: '',
    path: '/',
    active: true,
    icon: Home,
    accent: 'var(--accent-primary)',
    description: 'Landing page for the mini-build library.',
  },
  {
    name: 'Chuck Norris Jokes',
    link: 'chuckNorris',
    path: '/chuckNorris',
    icon: Laugh,
    accent: 'var(--accent-secondary)',
    description: 'Pulls random Chuck Norris jokes with category filtering.',
  },
  {
    name: 'Animated Text',
    link: 'animatedText',
    path: '/animatedText',
    icon: Type,
    accent: 'var(--accent-primary)',
    description: 'Applies animation presets to custom text input.',
  },
  {
    name: 'Loaders',
    link: 'loaders',
    path: '/loaders',
    icon: LoaderCircle,
    accent: 'var(--accent-secondary)',
    description: 'Loader demos with progress and async data states.',
  },
  {
    name: 'Truthy',
    link: 'truthy',
    path: '/truthy',
    icon: ToggleLeft,
    accent: 'var(--accent-primary)',
    description: 'Simple state demos showing truthy and toggle behaviour.',
  },
  {
    name: 'Flow Diagrams',
    link: 'reactflow',
    path: '/reactflow',
    icon: Workflow,
    accent: 'var(--accent-secondary)',
    description: 'Interactive flow diagrams built with React Flow.',
  },
  {
    name: 'Flip This',
    link: 'flip',
    path: '/flip',
    icon: RotateCcwSquare,
    accent: 'var(--accent-primary)',
    description: 'Card-flip interaction mini game.',
  },
  {
    name: 'Expanded',
    link: 'expand',
    path: '/expand',
    icon: Rows3,
    accent: 'var(--accent-secondary)',
    description: 'Expandable content section playground.',
  },
  {
    name: 'Pokemon API',
    link: 'pokemon',
    path: '/pokemon',
    icon: Sparkles,
    accent: 'var(--accent-primary)',
    description: 'Pokemon lookup with API-powered card views.',
  },
  {
    name: 'Password Gen',
    link: 'passGen',
    path: '/passGen',
    icon: KeyRound,
    accent: 'var(--accent-secondary)',
    description: 'Customisable password generation utility.',
  },
  {
    name: 'I & E',
    link: 'IandE',
    path: '/IandE',
    icon: Wallet,
    accent: 'var(--accent-primary)',
    description: 'Income and expense manager mini app.',
  },
  {
    name: 'RIO API',
    link: 'IOP',
    path: '/IOP',
    icon: ScanSearch,
    accent: 'var(--accent-secondary)',
    description: 'Intersection observer behaviour examples.',
  },
  {
    name: 'Kitty API',
    link: 'cat',
    path: '/cat',
    icon: Cat,
    accent: 'var(--accent-primary)',
    description: 'Cat API image feed experiments.',
  },
  {
    name: 'Sortables',
    link: 'sort',
    path: '/sort',
    icon: ArrowUpDown,
    accent: 'var(--accent-secondary)',
    description: 'Drag, reorder and sortable list examples.',
  },
  {
    name: 'Filters',
    link: 'filters',
    path: '/filters',
    icon: Filter,
    accent: 'var(--accent-primary)',
    description: 'Table filtering and export playground.',
  },
  {
    name: 'Date Pickers',
    link: 'datepickers',
    path: '/datepickers',
    icon: CalendarDays,
    accent: 'var(--accent-secondary)',
    description: 'Date picker variants and shortcuts.',
  },
  {
    name: 'Virtualized List',
    link: 'virtualized',
    path: '/virtualized',
    icon: List,
    accent: 'var(--accent-primary)',
    description: 'Virtualized rendering for large lists.',
  },
  {
    name: 'Leaderboard',
    link: 'leaderboard',
    path: '/leaderboard',
    icon: Trophy,
    accent: 'var(--accent-secondary)',
    description: 'Ranking and leaderboard score display.',
  },
  {
    name: 'CardSwap',
    link: 'cardswap',
    path: '/cardswap',
    icon: Hand,
    accent: 'var(--accent-primary)',
    description: 'Drag and drop card swap interaction.',
  },
  {
    name: 'Edit Section',
    link: 'editsection',
    path: '/editsection',
    icon: PencilRuler,
    accent: 'var(--accent-secondary)',
    description: 'Editable content block and layout editor.',
  },
  {
    name: 'DND Grid',
    link: 'dndgrid',
    path: '/dndgrid',
    icon: LayoutGrid,
    accent: 'var(--accent-primary)',
    description: 'Sortable masonry-style profile grid.',
  },
];
